### ISSUE TITLE
# 1 Create draft for Milestone 1

### ISSUE THREAD

**Issue by FrediThs** [xEgle/ds-ml-project-kickstarter#14]
Our stakeholder are Kickstarter’s decision makers. Their goal is to drive customer success and thereby the revenue from the successful projects fees.

Kickstarter has a “all or nothing” take on success for their projects: if a project does not reach its goal, the funds do not get collected nor transferred from backers’ bank accounts. 

Conclusion: if the pledged amount exceeds a goal, then it succeeded. We consider this as our main aim of maximising since they get a 5% fee of each successful project. According to Kickstarter data, approximately 36% of projects met their fundraising goals from 2009 to 2017.

**Goal of the Data Fighting Kickstart Turtles:** 
Create ML model that predicts wether or not a campaign is successful. 

**Value of Product:**
Being able to predict if a campaign will be successful and advice customers on factors for success.

**Prediction:**
A project on kickstarter is successful (1) or not (0). We measure this by looking at the state which is either successful or failed.

**Evaluation Metric:**
Since our data is nearly evenly distributed we will start with the Accuracy score. 

**Baseline Model:**
H1: Kickstarter is not equally well suited for all kinds of projects, therefore we expect some categories/sub-categories to be more likely to succeed 

If we factor in: 
H2: Some goals are just too high to be practical, others too low to be important we expect to reach a higher accuracy.

**Score:**
H1 Accuracy score: 0.56
H2 Accuracy score improves to 0.66 

**Conclusion:** 
- There are other factors that drive the success of the project 
- we need to redefine the category definition.

**Comment by henryklange** [comment]
Value of Product:
Being able to predict if a campaign will be successful and advice customers on factors for success

Prediction:
A project on kickstarter is successful (1) or not (0). We measure this by looking if the goal was at least reached for all projects that are completed.

Evaluation Metric:
Example: f1-score (recommended and given by Zindi)

Baseline Model:
H1: Kickstarter is not equally well suited for all kinds of projects, therefore we expect some categories/sub-categories to be more likely to succeed.

H2: The length of the name and/or description + filled profile details will lead to greater success because it engages people more and drives trust and therefore the likeliness to spend money.

Score:
HE: f1-score = 0.1
Success rate greater than baseline of 36%
