### ISSUE TITLE
#1 Define the value / hypothesis for the model

### ISSUE THREAD

**Issue by xEgle** [xEgle/ds-ml-project-kickstarter#3]
As ds I want to define hypothesis for my data task

**Acceptance criteria**
- We suggest some easy models for the crowd including metrics

**Add. info**
- We want to investigate the duration of projects, as we expect long running projects to be less successful

**Comment by FrediThs** [comment]
- Is it good to have a long description (=blob) and/or name 
- There are categories that are more success-full than others > e.g. medicals
- People that create more than one campaign are more successful than others
- Non-USD projects are less successful > e.g. USA is target market
- Is disable communication a feature that can be removed?

**Comment by FrediThs** [comment]
1— Which project categories are more likely to succeed?
2 —What is the association between project outcome and fundraising goals?
3 — Which categories are popular among backers and, among those, which subcategories highly fall behind their goal?

from https://towardsdatascience.com/how-do-you-succeed-on-kickstarter-c047c60085cf

**Comment by FrediThs** [comment]
1 - successful projects tend to have smaller (and therefore more realistic) goals — the median amount sought by successful projects is about half that of failed projects (medians are used due to high positive skew of funding and goal amounts).
2 - Successful projects have slightly shorter campaign lengths, but take slightly longer to launch (measured from the time the project was first created on the site).
3 - Roughly 20% of successful projects were highlighted on the site as staff picks. It does not seem unreasonable to suggest a causative relationship here, i.e. that projects that are chosen as staff picks are much more likely to go on to be successful, and that only a few staff picks go on to fail.
4 - The best project types to launch on Kickstarter are comics (on the grounds of success rate, number of backers and amount pledged), dance (success rate and amount pledged) and games (amount pledged and number of backers).
5 - timing Tuesday is the best day to launch a project, and weekends are the worst (the same pattern holds for the amount raised and the number of backers).
12pm to 2pm UTC is the best time to launch a project — it also has the greatest median number of backers and amount of funding. 6pm to 4am UTC is the worst time to launch.
October is the best month to launch a project — it also has the greatest median number of backers and amount of funding. July and December are the worst months.

https://towardsdatascience.com/using-machine-learning-to-predict-kickstarter-success-e371ab56a743

**Comment by FrediThs** [comment]
**Big topics**
I. Timing
II. Categories 
III. Goals 
IV. Influence of title and description
